### ISSUE TITLE
Please consider adding a license for the project

### ISSUE THREAD

**Issue by Dither** [milchchan/Apricot#3]
The project is very interesting but without license it is unknown what can be done with it. Please consider adding some kind of license. I recommend either [MIT](https://opensource.org/licenses/MIT) if you want a permissive license or [LGPL](https://opensource.org/licenses/LGPL-3.0) if you want any changed code to be open-sourced and licensed the same.
Thank you for sharing this application.

**Comment by milchchan** [comment]
Thank you for your interest in Apricot. I applied MIT License to this project. Check it out!
